[package]
name = "extract-link"
version = "0.1.0"
edition = "2021"

[dependencies]
error-chain = "0.12.4"
reqwest = { version = "0.12", features = ["blocking", "json" ] } 
select = "0.5.0"
tokio = { version = "1", features = ["full"] }
